[package]
name = "davison"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
#num-traits = "0.2.16"
rug = "1.20.1"

#[features]
#rug = ["num-traits"]
